version: "3.9"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: xc514xxx
      MYSQL_USER: wuxc
      MYSQL_PASSWORD: hellowuxc
      MYSQL_DATABASE: employees
      MYSQL_INITDB_SKIP_TZINFO: true
    ports:
      - "3306:3306"
  cm:
    image: xxxcrel/cm:latest
    container_name: cm
    ports:
      - "5147:5147"
    depends_on:
      - mysql
    restart: on-failure
  cm-frontend:
    image: xxxcrel/cm-frontend:latest
    container_name: cm-frontend
    ports:
      - "80:80"
