server:
  port: 5147
spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    banner-mode: off
  profiles:
    active: test
  mvc:
    throw-exception-if-no-handler-found: true