server:
  port: 5147
spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy/MM/dd
  main:
    banner-mode: off
  profiles:
    active: prod
  mvc:
    throw-exception-if-no-handler-found: true