server:
  port: 5147
spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    generate-ddl: true
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
    url: jdbc:h2:~/employees
    data: classpath:user.sql
    initialization-mode: always
  main:
    banner-mode: off
  h2:
    console:
      enabled: true